config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'wishes#index'
  
  resources :wishes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :wishes
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :user

  validates :title, :url, presence: true
  enum priority: [ :normal, :high, :very_high ] 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: [:edit, :update, :destroy, :show]
  before_action :validate_user, only: [:edit, :update, :destroy, :show]
  
  def index
    @wishes = current_user.wishes.order(:priority).reverse
  end

  def new
    @wish = Wish.new
  end

  def create
    @wish = Wish.new(wish_params)
    if @wish.save
      redirect_to wishes_path
    else
      redirect_to :new
    end
  end

  def edit
  end

  def update
    if @wish.update(wish_params)
      redirect_to wishes_path
    else
      redirect_to :edit
    end
  end

  def destroy
    @wish.delete
    redirect_to wishes_path
  end

  def show
  end


  private

  def wish_params
    params.require(:wish).permit( :title, :description, :url, :priority ).merge(user_id: current_user.id)
  end

  def validate_user
    redirect_to wishes_path if @wish.user != current_user    
  end

  def find_user
    @wish = Wish.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <%= link_to 'Wish List', root_path, class: 'navbar-brand' %>
    <%= link_to 'New wish', new_wish_path, class: 'nav-link'  %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/wishes/edit.html.erb
<h3>Edit Wish</h3>
<%= form_with model: @wish do |form| %>
  <p>Title<%= form.text_field :title %></p>
  <p>Description<%= form.text_area :description %></p>
  <p>Url<%= form.text_field :url %></p>
  <p>Priority<%= form.select :priority, Wish.priorities.keys.map { |p| [ p.titleize, p ] } %></p>
  <p><%= form.submit 'Submit' %></p>
<% end %>

app/views/wishes/index.html.erb
<div class="row row-cols-1 row-cols-md-3 m-3">
  <% @wishes.each do |wish| %>
    <div class="col mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5><%= link_to wish.title, wish_path(id: wish.id), class: 'card-title' %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= wish.priority.titleize %> Priority</h6>
          <p class="card-text"><%= truncate(wish.description, length: 150, omission: '... (continued)') %></p>
          <%= link_to 'Go to link', wish.url, class: 'card-link', target: '_blank' %>
          <%= link_to 'Edit', edit_wish_path(id: wish.id), class: 'card-link' %>
          <%= link_to 'Destroy', wish_path(id: wish.id), method: :delete, data: {confirm: "Are you sure?"}, class: 'card-link' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/wishes/new.html.erb
<h3>New Wish</h3>
<%= form_with model: @wish do |form| %>
  <p>Title<%= form.text_field :title %></p>
  <p>Description<%= form.text_area :description %></p>
  <p>Url<%= form.text_field :url %></p>
  <p>Priority<%= form.select :priority, Wish.priorities.keys.map { |p| [ p.titleize, p ] } %></p>
  <p><%= form.submit 'Submit' %></p>
<% end %>

app/views/wishes/show.html.erb
<h2><%= @wish.title.titleize %></h2>
<p><%= @wish.description %></p>
<p><%= @wish.url %></p>
<p><%= @wish.priority.titleize %></p>